name: 'Setup Proxy Feature Dependencies - Linux GNOME'
description: 'Setup GNOME-specific dependencies for proxy tests on Linux'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies and setup environment
      shell: bash
      run: |
        # Install all required packages in one go
        sudo apt-get update
        sudo apt-get --no-install-recommends install -y \
          dconf-cli gsettings-desktop-schemas glib-2.0-dev dbus-x11 \
          libglib2.0-0 libnss3 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 \
          libcups2 libgtk-3-0 libasound2t64 xvfb

        # Setup display and D-Bus environment
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 2

        # Setup D-Bus session for GNOME gsettings
        eval $(dbus-launch --sh-syntax)
        export DBUS_SESSION_BUS_ADDRESS
        echo "D-Bus session: $DBUS_SESSION_BUS_ADDRESS"

        # Setup Electron sandbox permissions
        sudo chown root /home/runner/work/bruno/bruno/node_modules/electron/dist/chrome-sandbox
        sudo chmod 4755 /home/runner/work/bruno/bruno/node_modules/electron/dist/chrome-sandbox