name: CA certs tests for linux os
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'runner for both cli and e2e tests'
        required: false
        default: 'ubuntu-latest'
        type: string
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cli_tests:
    name: cli tests
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v22.17.0

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          npm ci --legacy-peer-deps

      - name: build libraries
        run: |
          npm run build --workspace=packages/bruno-query
          npm run build --workspace=packages/bruno-common
          npm run sandbox:bundle-libraries --workspace=packages/bruno-js
          npm run build --workspace=packages/bruno-converters
          npm run build --workspace=packages/bruno-requests
          npm run build --workspace=packages/bruno-filestore

      - name: setup CA certificates and start the ca certs server
        id: ca-server
        uses: ./.github/actions/server_with_ca_certs/linux

      - name: run cli tests
        run: |
          set -euo pipefail
          
          # navigate to CA certificates test collection directory
          cd e2e-tests/ca_certs/collection

          echo "with ssl/tls disabled"
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit1.xml --insecure --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit1.xml | grep -q "^1$" || exit 1

          echo "with default/sytem ca certs"
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit2.xml --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit2.xml | grep -q "^1$" || exit 1

          echo "with only VALID custom ca cert and NO default/system ca certs"
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit3.xml --cacert ../server/certs/ca-cert.pem --ignore-truststore --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit3.xml | grep -q "^1$" || exit 1

          echo "with INVALID custom ca cert and default/system ca certs"
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit4.xml --cacert ../server/certs/ca-cert.key --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit4.xml | grep -q "^1$" || exit 1

          echo "with INVALID custom ca cert and NO default/system ca certs"
          echo "request will error but the pre-request test should pass"
          # should fail
          node ../../../packages/bruno-cli/bin/bru.js run ./request_with_fail_test_case.bru --output junit5.xml --cacert ../server/certs/ca-key.pem --ignore-truststore --format junit --donotbailonerror
          xmllint --xpath 'count(//testsuite[@errors="1"])' junit5.xml | grep -q "^1$" || exit 1

  e2e_tests:
    name: e2e tests
    timeout-minutes: 60
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: v22.17.0
    
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get --no-install-recommends install -y \
          libglib2.0-0 libnss3 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgtk-3-0 libasound2t64 \
          xvfb
        npm ci --legacy-peer-deps
        sudo chown root /home/runner/work/bruno/bruno/node_modules/electron/dist/chrome-sandbox
        sudo chmod 4755 /home/runner/work/bruno/bruno/node_modules/electron/dist/chrome-sandbox

    - name: build libraries
      run: |
        npm run build:graphql-docs
        npm run build:bruno-query
        npm run build:bruno-common
        npm run sandbox:bundle-libraries --workspace=packages/bruno-js
        npm run build:bruno-converters
        npm run build:bruno-requests
        npm run build:bruno-filestore

    - name: setup CA certificates and start the ca certs server
      id: ca-server
      uses: ./.github/actions/server_with_ca_certs/linux

    - name: run e2e tests
      run: |
        xvfb-run npm run test:e2e ca_certs

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-linux
        path: playwright-report/
        retention-days: 30