name: CA certs tests for windows os
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'runner for both cli and e2e tests'
        required: false
        default: 'windows-latest'
        type: string
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cli_tests:
    name: cli tests
    runs-on: ${{ inputs.runner || 'windows-latest' }}
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: install PowerShell Core
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          Write-Output "Installing PowerShell Core (pwsh)..."
          
          # Install PowerShell Core using winget (available on GitHub Actions runners)
          winget install --id Microsoft.Powershell --source winget --accept-package-agreements --accept-source-agreements
          
          # Add PowerShell Core to PATH for current session
          $pwshPath = "${env:ProgramFiles}\PowerShell\7"
          if (Test-Path $pwshPath) {
            $env:PATH = "$pwshPath;$env:PATH"
            Write-Output "PowerShell Core installed and added to PATH"
          } else {
            Write-Output "Error: PowerShell Core installation failed"
            exit 1
          }
      - name: install OpenSSL with Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install openssl -y
          refreshenv
      - uses: actions/setup-node@v4
        with:
          node-version: v22.17.0

      - name: install dependencies
        shell: pwsh
        run: npm ci --legacy-peer-deps

      - name: build libraries
        shell: pwsh
        run: |
          npm run build --workspace=packages/bruno-query
          npm run build --workspace=packages/bruno-common
          npm run sandbox:bundle-libraries --workspace=packages/bruno-js
          npm run build --workspace=packages/bruno-converters
          npm run build --workspace=packages/bruno-requests
          npm run build --workspace=packages/bruno-filestore

      - name: setup CA certificates and start the ca certs server
        id: ca-server
        uses: ./.github/actions/server_with_ca_certs/windows

      - name: run cli tests
        shell: pwsh
        run: |
          Set-Location "e2e-tests\ca_certs\collection"

          Write-Host "with ssl/tls disabled"
          node "..\..\..\packages\bruno-cli\bin\bru.js" run ".\request.bru" --output "junit1.xml" --insecure --format junit
          if (-not (Select-String -Path "junit1.xml" -Pattern 'errors="0"' -Quiet)) { exit 1 }

          Write-Host "with default/system ca certs"
          node "..\..\..\packages\bruno-cli\bin\bru.js" run ".\request.bru" --output "junit2.xml" --format junit
          if (-not (Select-String -Path "junit2.xml" -Pattern 'errors="0"' -Quiet)) { exit 1 }

          Write-Host "with only VALID custom ca cert and NO default/system ca certs"
          node "..\..\..\packages\bruno-cli\bin\bru.js" run ".\request.bru" --output "junit3.xml" --cacert "..\server\certs\ca-cert.pem" --ignore-truststore --format junit
          if (-not (Select-String -Path "junit3.xml" -Pattern 'errors="0"' -Quiet)) { exit 1 }

          Write-Host "with INVALID custom ca cert and default/system ca certs"
          node "..\..\..\packages\bruno-cli\bin\bru.js" run ".\request.bru" --output "junit4.xml" --cacert "..\server\certs\ca-cert.key" --format junit
          if (-not (Select-String -Path "junit4.xml" -Pattern 'errors="0"' -Quiet)) { exit 1 }

          Write-Host "with INVALID custom ca cert and NO default/system ca certs"
          Write-Host "request will error but the pre-request test should pass"
          node "..\..\..\packages\bruno-cli\bin\bru.js" run ".\request_with_fail_test_case.bru" --output "junit5.xml" --cacert "..\server\certs\ca-key.pem" --ignore-truststore --format junit --donotbailonerror
          if (-not (Select-String -Path "junit5.xml" -Pattern 'errors="1"' -Quiet)) { exit 1 }

  e2e_tests:
    name: e2e tests
    timeout-minutes: 60
    runs-on: ${{ inputs.runner || 'windows-latest' }}
    steps:
    - uses: actions/checkout@v4
    - name: install PowerShell Core
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        Write-Output "Installing PowerShell Core (pwsh)..."
        
        # Install PowerShell Core using winget (available on GitHub Actions runners)
        winget install --id Microsoft.Powershell --source winget --accept-package-agreements --accept-source-agreements
        
        # Add PowerShell Core to PATH for current session
        $pwshPath = "${env:ProgramFiles}\PowerShell\7"
        if (Test-Path $pwshPath) {
          $env:PATH = "$pwshPath;$env:PATH"
          Write-Output "PowerShell Core installed and added to PATH"
        } else {
          Write-Output "Error: PowerShell Core installation failed"
          exit 1
        }
    - name: install OpenSSL with Chocolatey
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        choco install openssl -y
        refreshenv
    - uses: actions/setup-node@v4
      with:
        node-version: v22.17.0
    
    - name: install dependencies
      shell: pwsh
      run: npm ci --legacy-peer-deps

    - name: build libraries
      shell: pwsh
      run: |
        npm run build:graphql-docs
        npm run build:bruno-query
        npm run build:bruno-common
        npm run sandbox:bundle-libraries --workspace=packages/bruno-js
        npm run build:bruno-converters
        npm run build:bruno-requests
        npm run build:bruno-filestore

    - name: setup CA certificates and start the ca certs server
      id: ca-server
      uses: ./.github/actions/server_with_ca_certs/windows

    - name: run e2e tests
      shell: pwsh
      run: npm run test:e2e ca_certs

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-windows
        path: playwright-report/
        retention-days: 30