name: CA certs tests for mac os
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cli_tests:
    name: cli tests
    runs-on: self_hosted_macos
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v22.17.0

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install xmllint
        run: brew install libxml2

      - name: Build Libraries
        run: |
          npm run build --workspace=packages/bruno-query
          npm run build --workspace=packages/bruno-common
          npm run sandbox:bundle-libraries --workspace=packages/bruno-js
          npm run build --workspace=packages/bruno-converters
          npm run build --workspace=packages/bruno-requests
          npm run build --workspace=packages/bruno-filestore

      - name: setup CA certificates and start the ca certs server
        id: ca-server
        uses: ./.github/actions/server_with_ca_certs/mac

      - name: start the ca certs server and run tests
        run: |
          set -euo pipefail
          
          # navigate to CA certificates test collection directory
          cd e2e-tests/ca_certs/collection

          # with ssl/tls disabled
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit1.xml --insecure --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit1.xml | grep -q "^1$" || exit 1

          # with default/sytem ca certs
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit2.xml --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit2.xml | grep -q "^1$" || exit 1

          # with only VALID custom ca cert and NO default/system ca certs
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit3.xml --cacert ../server/certs/ca-cert.pem --ignore-truststore --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit3.xml | grep -q "^1$" || exit 1

          # with INVALID custom ca cert and default/system ca certs
          # should pass
          node ../../../packages/bruno-cli/bin/bru.js run ./request.bru --output junit4.xml --cacert ../server/certs/ca-cert.key --format junit
          xmllint --xpath 'count(//testsuite[@errors="0"])' junit4.xml | grep -q "^1$" || exit 1

          # with INVALID custom ca cert and NO default/system ca certs
          # should fail
          node ../../../packages/bruno-cli/bin/bru.js run ./request_with_fail_test_case.bru --output junit5.xml --cacert ../server/certs/ca-key.pem --ignore-truststore --format junit --donotbailonerror
          xmllint --xpath 'count(//testsuite[@errors="1"])' junit5.xml | grep -q "^1$" || exit 1

      # - name: publish CA certs test report
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     check_name: CA certs test results
      #     files: |
      #       packages/bruno-tests/ca_certs/collection/junit1.xml
      #       packages/bruno-tests/ca_certs/collection/junit2.xml
      #       packages/bruno-tests/ca_certs/collection/junit3.xml
      #       packages/bruno-tests/ca_certs/collection/junit4.xml
      #       packages/bruno-tests/ca_certs/collection/junit5.xml
      #     comment_mode: always


  e2e_tests:
    name: e2e tests
    timeout-minutes: 60
    runs-on: self_hosted_macos
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: v22.17.0
    - name: Install dependencies
      run: |
        npm ci --legacy-peer-deps

    - name: Build Libraries
      run: |
        npm run build:graphql-docs
        npm run build:bruno-query
        npm run build:bruno-common
        npm run sandbox:bundle-libraries --workspace=packages/bruno-js
        npm run build:bruno-converters
        npm run build:bruno-requests
        npm run build:bruno-filestore

    - name: setup CA certificates and start the ca certs server
      id: ca-server
      uses: ./.github/actions/server_with_ca_certs/mac

    - name: run tests
      run: |
        set -euo pipefail

        npm run test:e2e ca_certs

    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report-macos
    #     path: playwright-report/
    #     retention-days: 30
